# Inspired by https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/ci.yaml
# but tweaked in several ways.  If you make changes here, consider doing so across other
# repositories in e.g. ostreedev etc.
name: CI

permissions:
  actions: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo ./ci/installdeps.sh
      - name: Build
        run: make -C /usr/src/linux modules M=$PWD
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          path: ostreefs.ko
          if-no-files-found: error 
  integration:
    name: "Integration"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: ostreefs.ko
      - name: Run tests
        run: sudo ci/tests.sh
